### ISSUE TITLE
Ranking question can't be reordered on Android mobile device

### ISSUE THREAD

**Issue by timblake78** [surveyjs/survey-library#5813] opened 2023-03-20 04:00 UTC
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

Can't reorder ranking questions on Android mobile devices.  Therefore, if a ranking question is required then the survey can't be completed.

### What is the expected behavior?

Ranking answers can be dragged into the preferred order, as they can on iOS mobile devices.

### How would you reproduce the current behavior (if this is a bug)?

Using the ranking question in the simple question examples:
https://surveyjs.io/form-library/examples/add-ranking-question-to-form/jquery

Using an android mobile device.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

https://surveyjs.io/form-library/examples/add-ranking-question-to-form/jquery

Test code

https://surveyjs.io/form-library/examples/add-ranking-question-to-form/jquery

### Specify your

* browser: Chrome
* browser version: Unknown
* surveyjs platform (angular or react or jquery or knockout or vue): JQuery
* surveyjs version: 1.9.x

**Comment by dmitrykurmanov** [comment] 2023-03-20 10:08
Unfortunately, I can't manage to reproduce the problem on my device. The problem might be linked to the `longTap` functionality. By default, the `longTap` is "on" and you need to tap a while to start dragging. You could also try to "off" this functionality by the following code:

```js
{
      "type": "ranking",
      "longTap": false
}
```

But I recommend not doing it because it might cause a collision with the "scroll" action on mobile devices.

**Comment by JaneSjs** [comment] 2023-03-20 10:18
Hello @timblake78,
I captured a screencast demonstrating how Ranking operates on my mobile phone. Please let me know if you can now reorder items.

https://user-images.githubusercontent.com/22372972/226311052-1900d90a-0b39-4d0a-a7e1-f2a35549c1eb.mp4

**Comment by JaneSjs** [comment] 2023-11-07 08:38
Hello @timblake78,
I'm closing this issue for now. Please feel free to reactivate this thread if you encounter any issues or have further questions.

Thanks

**Closed by JaneSjs** 2023-11-07 08:38 UTC
Labels: question, need more info, user issue
