### ISSUE TITLE
Preview. A couple of issues (Safari).

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#6314] opened 2023-06-06 07:59 UTC
- [ ] rating items disappear during editing
- [ ] broken CSS 

https://github.com/surveyjs/survey-library/assets/17025812/804fb92e-0924-47d8-b4f1-4a6d12da747b

![Image](https://github.com/surveyjs/survey-library/assets/17025812/3b4fa1cd-e769-4772-8da1-5ecd91601bb8)

**Comment by mikeamelin** [comment] 2023-06-06 07:59
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question1",
     "choices": [
      "Item 1",
      "Item 2",
      "Item 3"
     ]
    },
    {
     "type": "rating",
     "name": "question5"
    }
   ]
  },
  {
   "name": "page2",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question2",
     "choices": [
      "Item 1",
      "Item 2",
      "Item 3"
     ]
    },
    {
     "type": "boolean",
     "name": "question6"
    }
   ]
  }
 ],
 "showPreviewBeforeComplete": "showAllQuestions"
}

**Comment by dk981234** [comment] 2023-06-07 13:05
Can't reproduce.
Seems to be fixed via this pull request: https://github.com/surveyjs/survey-library/pull/6280.

**Closed by dk981234** 2023-06-07 13:05 UTC
Labels: bug
