### ISSUE TITLE
Date input field - lost focus on chaning if question has an error

### ISSUE THREAD

**Issue by diana-omer-ali** [surveyjs/survey-library#4037] opened 2022-02-18 10:19 UTC
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug.

### What is the current behavior?
Steps:
- write a date that goes in error according to validator
- try to change manually either the day or the month  (2 digits)

 **Result**: the first digit is not typed 

### What is the expected behavior?

I should be able to enter the 2 digit day or month

### How would you reproduce the current behavior (if this is a bug)?

See below section

#### Provide the test code and the tested page URL (if applicable)
Paste the following code  in https://surveyjs.io/create-survey: 

{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question1",
     "requiredErrorText": "Wrong date",
     "validators": [
      {
       "type": "expression",
       "expression": "{question1} = '2022-02-18'"
      }
     ],
     "inputType": "date"
    }
   ]
  }
 ]
}

You should get this:
![image](https://user-images.githubusercontent.com/99958703/154663514-df5e7edf-f985-4200-82a3-e7cb8177ced3.png)

Try to change the month OR day to see the issue

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment] 2022-02-22 07:22
@diana-omer-ali Yes, we do no compare errors object correctly and it leads to this behavior.
I have fixed by the commit above.

Thank you,
Andrew

**Comment by diana-omer-ali** [comment] 2022-02-22 07:58
Thank you Andrew for your quick response.
I was testing it today on survey.io the same example as above and i notice another strange behavior (maybe you already fix it)
Steps:
-  write a date that goes in error according to validator
-  try to change the year and then you see that the entire date is reset 
![image](https://user-images.githubusercontent.com/99958703/155087484-5da04c26-cec7-4d28-9c64-4cebeb7df215.png)

**Closed** 2022-02-22 07:59 UTC

**Comment by diana-omer-ali** [comment] 2022-02-22 08:24
Hi Andrew. I saw you close the issue. If i take the last version 1.9.14 from here https://www.npmjs.com/package/survey-angular, will that contain your changes? 
Thanks

**Comment by tsv2013** [comment] 2022-02-24 09:35
The issue is marked as resolved in 1.9.15
