### ISSUE TITLE
Surveyjs own css styles override Angular component (surveyjs.component.scss) styles

### ISSUE THREAD

**Issue by halexiev-hedgeserv** [surveyjs/survey-library#939] opened 2018-02-19 13:07 UTC
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

**When surveyjs is used in a standard angular component like this:**
  surveyjs.component.html
  surveyjs.component.scss
  surveyjs.component.ts

then style definitions in surveyjs override style definitions in **surveyjs.component.scss**.

### What is the expected behavior?

If I have a custom definition for the **.sv_p_title** surveyjs css class it should override same class in surveyjs own css styles.

### How would you reproduce the current behavior (if this is a bug)?

Add following in **surveyjs.component.scss**:

.sv_p_title {
  color: #red;
}

Run the app with panels in the json and observe panels title color - it is **not** red.

As a workaround - if I import **surveyjs.component.scss** styles in global **styles.css** the custom definitions work as expected, but this is obviously not how it should be.

A better way would be to provide custom css class names for parts that need to be customised, but this is also not an ideal solution as surveyjs does not provide hooks to define custom css classes for all possible points of interest. For example the **Survey.defaultBootstrapMaterialCss.question.mainRoot** css class hook does not represent the outermost question div element, so it is not straightforward to add even/odd question background highlighting.

### Specify your

* browser: chrome
* browser version: 64
* surveyjs platform (angular or react or jquery or knockout or vue): angular cli
* surveyjs version: 1.0.9

**Comment by tsv2013** [comment] 2018-02-20 05:51
Probably duplicate of the https://github.com/surveyjs/surveyjs/issues/900 - How to apply customised CSS in surveyjs-react?

You sould use more specific selector. But your CSS works ok for me in this plunk - https://plnkr.co/edit/VKhI13?p=preview

```CSS
.sv_p_title {
    color: red;
}
```

**Comment by halexiev-hedgeserv** [comment] 2018-02-22 13:18
@tsv2013 The plunk obviously does not use angular cli version as specified in the description above.

Can you please check PR: https://github.com/surveyjs/surveyjs_angular_cli/pull/7

Thanks,
Hristo

**Comment by halexiev-hedgeserv** [comment] 2018-02-26 10:11
Hi guys,

Have you had any time to have a look at this issue?

Thanks,
Hristo

**Comment by tsv2013** [comment] 2018-02-26 10:56
@halexiev-hedgeserv  Haven't yet, I'll take a look.

**Comment by tsv2013** [comment] 2018-02-26 11:39
@halexiev-hedgeserv This question is not related to the SurveyJS library. This CSS scoping feature of angulat components. It is described in the Angular documentation: https://angular.io/guide/component-styles

Component styles should include spesicific selectors, in your case:
```CSS
:host /deep/ .sv_q_title {
  color: red;
}
```

Hope this helps

**Comment by halexiev-hedgeserv** [comment] 2018-02-26 12:26
@tsv2013 Yes, absolutely helps, thank you!

**Closed** 2019-09-05 14:00 UTC
Labels: question
