### ISSUE TITLE
isLocalizable does not work well with custom questions

### ISSUE THREAD

**Issue by MaksSlesarenko** [surveyjs/survey-library#7003] opened 2023-09-23 11:48 UTC
First we add custom property to all of our questions. 

`Serializer.addProperty('question', { name: 'tooltip', category: 'general', isLocalizable: true, visibleIndex: 3 });`

and that works fine.

Until we add custom question 

`export class MyQuestionModel extends Question {
    getType() {
        return MY_QUESTION_TYPE;
    }
}`
Than we get errors

`Uncaught TypeError: Cannot read properties of undefined (reading 'text')
    at e.getObjPropertyValueCore (1713.82a224eb.chunk.js:2:465295)
    at e.getObjPropertyValue (1713.82a224eb.chunk.js:2:464879)
    at t.getDataValueCore (1713.82a224eb.chunk.js:2:1181395)
    at t.getValue (1713.82a224eb.chunk.js:2:1242622)
    at t.updateAllQuestionsValue (1713.82a224eb.chunk.js:2:1229863)
    at t.setDataCore (1713.82a224eb.chunk.js:2:1178085)
    at t.set (1713.82a224eb.chunk.js:2:1179302)
    at e.setObj (1713.82a224eb.chunk.js:2:4046549)
    at e.set (1713.82a224eb.chunk.js:2:4043347)
    at t.selectionChanged (1713.82a224eb.chunk.js:2:3803553)`

After some investigation I've found out that LocalizableString object is not created for our 'tooltip' property therefore `obj.loctooltip ` is undefined 

` JsonMetadata.prototype.getObjPropertyValueCore = function (obj, prop) {
      ...
            if (!!prop.serializationProperty)
                return obj[prop.serializationProperty].text;
        }
        ...
    };`

As a workaround, I have to initialise it manually:

`export class MyQuestionModel extends Question {
    protected loctooltip: LocalizableString = this.createLocalizableString('tooltip', this, true);
    getType() {
        return MY_QUESTION_TYPE;
    }
}`

PS "survey-react-ui": "^1.9.107-109",

**Comment by andrewtelnov** [comment] 2023-09-25 12:04
@MaksSlesarenko Here is [the example](https://codesandbox.io/s/sleepy-galileo-z9gzwf) that doesn't produce the error.
Could you please correct it so it produces an error or provide another example that we can debug and find the initial issue.

Thank you,
Andrew

**Comment by andrewtelnov** [comment] 2023-10-09 09:18
@MaksSlesarenko I am closing the issue, since we can't reproduce it. Please feel free to contact us.

Thank you,
Andrew

**Closed by andrewtelnov** 2023-10-09 09:18 UTC
Labels: question
