### ISSUE TITLE
Multiple Text doesn't pass validation when checkErrorsMode is set to onValueChanging

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-library#5201] opened 2022-11-08 15:53 UTC
Run [this example](https://plnkr.co/edit/EdqZwiyOoqfoxPCx). Enter the min value: the error appears and remains even if you enter a correct max value.
![image](https://user-images.githubusercontent.com/22372972/200612350-20af855a-3d9d-4f17-a0de-1c7037c1e8d2.png)

If works with the default `checkErrorsMode`: https://plnkr.co/edit/eflMNWhpQMRvgibq.

**Comment by RomanTsukanov** [comment] 2022-11-09 05:58
Duplicate of #5190

**Closed by RomanTsukanov** 2022-11-09 05:58 UTC
Labels: bug

**Comment by JaneGaid** [comment] 2022-11-09 06:01
Dup: https://github.com/surveyjs/survey-library/issues/5190
