### ISSUE TITLE
Survey Preview displays an empty detail form

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#9175] opened 2024-12-17 06:59 UTC
T21023 - Adding a row after expanding "detailElements" put the new row above the detail element
https://surveyjs.answerdesk.io/internal/ticket/details/T21023
***
https://github.com/user-attachments/assets/64e092ea-187c-4809-85b7-e3160ed60281
```
{
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "matrixdynamic",
          "name": "contacts",
          "title": "Contact list",
          "columns": [
            {
              "name": "first-name",
              "title": "First name",
              "cellType": "text",
              "isRequired": true,
              "maxLength": 25
            },
            {
              "name": "last-name",
              "title": "Last name",
              "cellType": "text",
              "isRequired": true,
              "maxLength": 25
            }
          ],
          "detailElements": [
            {
              "type": "text",
              "name": "phone",
              "title": "Phone",
              "isRequired": true,
              "inputType": "tel"
            },
            {
              "type": "text",
              "name": "email",
              "startWithNewLine": false,
              "title": "Email",
              "isRequired": true,
              "inputType": "email"
            }
          ],
          "detailPanelMode": "underRowSingle",
          "rowCount": 1,
          "confirmDelete": true,
          "confirmDeleteText": "Are you sure you want to delete this contact?",
          "addRowText": "Add a contact",
          "removeRowText": "Delete the contact",
          "detailPanelShowOnAdding": true
        }
      ]
    }
  ],
  "showQuestionNumbers": "off",
  "checkErrorsMode": "onValueChanged",
  "showPreviewBeforeComplete": "showAnsweredQuestions"
}
```

**Comment by andrewtelnov** [comment] 2024-12-17 14:55
The issue is fixed by [this PR](https://github.com/surveyjs/survey-library/pull/9145).
We have rewrite the code to show preview completely. As result this issue has been fixed.

Thank you,
Andrew

**Closed by andrewtelnov** 2024-12-17 14:55 UTC
Labels: bug, user issue
