### ISSUE TITLE
native dropdown with obsolete bootstrap theme

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#6498] opened 2023-07-10 12:28 UTC
### Are you requesting a feature, reporting a bug or asking a question?

bug/question

### What is the current behavior?

I am trying to use the new dropdown with bootstrap. 

https://plnkr.co/edit/zpbOPr8nhV418Zh2 (derived from [here](https://surveyjs.io/form-library/examples/bootstrap-theme/reactjs))

I noticed some obvious problems:

1. when I select a choice the field is not populated until I click somewhere else
2. the caret does not open the choices menu
3. wrong rendering of the choices menu (see figure below)

<img width="1116" alt="image" src="https://github.com/surveyjs/survey-library/assets/454321/2cf218a4-182e-43de-9eb1-e763481924b4">
 
Hope you can help even if I know that bootstrap is not supported anymore. 

Thanks a lot

**Comment by masciugo** [comment] 2023-07-12 14:36
thank you @OlgaLarina for taking care of this issue. I am afraid that some problems still remains. 

https://plnkr.co/edit/zpbOPr8nhV418Zh2?preview

### first problem

If the choice has a long label, after selection it results truncated until I click somewhere else:

<img width="1183" alt="image" src="https://github.com/surveyjs/survey-library/assets/454321/675ae7be-64d8-44ae-9a58-46d0e3bb5482">

I think this has something to do with the search feature, in fact it does not happen when `"searchEnabled": false`

Also when I search for long label something ugly happen. Just type _long_ ...

<img width="466" alt="image" src="https://github.com/surveyjs/survey-library/assets/454321/bf05d3e7-bbeb-4146-904e-7082ee80902c">

### second problem

when I select the other item the caret has a wrong position

<img width="457" alt="image" src="https://github.com/surveyjs/survey-library/assets/454321/77b987f5-12aa-4e15-af39-0dcffbf3d03c">

### third problem
the clear button does not work with the menu open




please don't hate me and tell me if I should open another issue. Thank you

**Comment by OlgaLarina** [comment] 2023-07-13 09:04
Hello @masciugo 
I will try to fix these issues.
Right now we're working active on the Theme Builder feature of the Survey Creator V2.

This feature will assist user to modify survey look and feel according his needs. 10 new themes will be introduced. End-users will be able to customize colors, paddings, font styles, panels transparency and other settings. Working on this feature we've solved this issue - moved CSS variables from body to survey root element.

In the nearest future (somewhere in a half-year) we're going to release version 2 of our products. In this major update we're going to deprecate all legacy themes: default (and modifications), modern and bootstrap.

**Comment by masciugo** [comment] 2023-08-24 14:18
thank you all for your work. Only the second part of my point 1 still happen in v1.9.104

> [...]
> Also when I search for long label something ugly happen. Just type long ...
> <img width="1096" alt="image" src="https://github.com/surveyjs/survey-library/assets/454321/44ed05e0-17c1-4757-905c-5569b41bde31">
> 

you can try yourself by the following updated plunk

https://plnkr.co/edit/VUFmrUSIL8KpCIQJ?preview

thank you

**Comment by masciugo** [comment] 2023-09-13 09:28
@OlgaLarina In few words the search field should keep only the typed search text 

I understand that's not a priority but maybe, hopefully, it's a small fix... :)

**Comment by JaneSjs** [comment] 2023-11-17 08:26
@masciugo It appears that the issue is not specific to a Bootstrap theme. We will research it and post updates in the following thread: https://github.com/surveyjs/survey-library/issues/7369.

Thanks

**Closed by JaneSjs** 2023-11-17 08:25 UTC
Labels: question, user issue
