### ISSUE TITLE
Cannot enable the Single Matrix | Require answer for all rows property by default

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5851] opened 2023-03-22 14:12 UTC
[Original issue](https://surveyjs.answerdesk.io/internal/ticket/details/T12458)
[Example](https://codesandbox.io/s/billowing-fast-r43wts?file=/src/SurveyCreatorComponent.jsx)

**Comment by andrewtelnov** [comment] 2023-03-22 19:40
The issue is fixed by this [PR](https://github.com/surveyjs/survey-library/pull/5849).

Thank you,
Andrew

**Closed** 2023-03-29 08:10 UTC
Labels: bug, user issue
