### ISSUE TITLE
Reference to null object error in matrix-rubric in preview page because of "paneldynamic" 

### ISSUE THREAD

**Issue by PPTA22** [surveyjs/survey-library#2602] opened 2021-01-08 04:14 UTC
### What is the current behavior?
incorrect showing matrix-rubric in preview page because of using "paneldynamic"
just showing a big black circle in the middle of the page

### What is the expected behavior?
correctly show the matrix-rubric in the preview page, 

### How would you reproduce the current behavior (if this is a bug)?

plz find the html file in the attachment(zip file)
[test.zip](https://github.com/surveyjs/survey-library/files/5785174/test.zip)

### Specify your
* browser: firefox 84.0.1 / edge(chromium)
* surveyjs version: latest

**Comment by andrewtelnov** [comment] 2021-01-08 08:16
@PPTA22 Could you please point to the issue? Here is [your example on plunker](https://plnkr.co/edit/gcDu7PKdPlMLO5EE).

Thank you,
Andrew

**Comment by PPTA22** [comment] 2021-01-08 12:58
sorry for the late reply, please also add the preview setting, then you would see that the survey preview page is not showing properly
![image](https://user-images.githubusercontent.com/40493117/104018035-2fd73580-5187-11eb-946b-24ec42d0eb6d.png)
![image](https://user-images.githubusercontent.com/40493117/104018078-3c5b8e00-5187-11eb-9561-014d2987da43.png)

**Comment by andrewtelnov** [comment] 2021-01-08 13:11
@PPTA22 I can't reproduce the issue in my example. Could you please fork my example and modify it so it doesn't work or modify your example and make it works.

Thank you,
Andrew

**Comment by PPTA22** [comment] 2021-01-08 13:15
try this
https://plnkr.co/edit/4YNL20yJPr1DpVc6

**Comment by andrewtelnov** [comment] 2021-01-08 13:23
@PPTA22 It works fine on my side. I have tried it in Chrome, FireFox and IE. Did you apply your changes in this plunker?

Thank you,
Andrew

**Comment by PPTA22** [comment] 2021-01-08 13:27
In my firefox, Edge both have this issue, the only thing i added on your plunker is 
`survey.showPreviewBeforeComplete = 'showAnsweredQuestions';`

this problem not only happened in one computer, i was using my office computer, then now I am using my own computer,
both of them have this issue
![image](https://user-images.githubusercontent.com/40493117/104020371-189a4700-518b-11eb-8a54-ed53d118689c.png)

![image](https://user-images.githubusercontent.com/40493117/104020328-03bdb380-518b-11eb-83d4-af710f6f20d6.png)

**Comment by andrewtelnov** [comment] 2021-01-08 13:33
@PPTA22 I did not click on "Preview" button. Got it now.

Thank you,
Andrew

**Comment by PPTA22** [comment] 2021-01-08 13:37
Thank you 👍

**Comment by andrewtelnov** [comment] 2021-01-08 18:04
@PPTA22 The bug is fixed by the commit above. We will include the fix in [v1.8.24](https://surveyjs.io/WhatsNew#v1.8.24).

Thank you,
Andrew

**Comment by PPTA22** [comment] 2021-01-09 01:29
Thank you so much  👍

**Closed** 2021-01-13 15:03 UTC
Labels: bug, fixed
