### ISSUE TITLE
React: Improve performance by not rendering collapsed panels

### ISSUE THREAD

**Issue by marc0n3** [surveyjs/survey-library#1763] opened 2019-07-17 07:17 UTC
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
We have a long survey of 100 questions in a single page, some are complex like matrixdropdowns.
Actually, on mobile, the survey takes 3seconds to start on the first rendering.
Our questions are categorized into different panels (arguments).

Inspecting the code we've found that we can do something like:

`
class SurveyPanelBlu extends SurveyPanel {
	
	renderContent(style, rows) {
		if (this.props.element.isCollapsed) return;
		return super.renderContent(style, rows);
	}

}
`

to render the panel content only if the panel is open.

By our initial test, the model remains consistent and the solution is working.
Our next step will be avoid subsequent rendering on collapse/reopen by using a semaphore.
This will be similar to the logic adopted by react-bootstrap Tabs
https://react-bootstrap.github.io/components/tabs/#tabs-props
in particular unmountOnExit and mountOnEnter

Do you foretell any particular issue?

Thanks

**Comment by andrewtelnov** [comment] 2019-07-17 08:01
@marc0n3 It makes perfect sense to do it in this way. I have modify our code. We are going to release a new minor version today, the changes will be included.

Thank you,
Andrew

**Comment by marc0n3** [comment] 2019-07-18 09:01
@andrewtelnov it seems that there is no firstLoad semaphore that avoid removing the panel on collapse.
Am I right?

By doing this the panel keeps re-rendering on each expand/collapse.
This can be another improvement, IMHO.

A good way to implement this can be the strategy adopted by react-bootstrap with the mountOnEnter and unMountOnExit props.

**Comment by marc0n3** [comment] 2019-07-19 17:01
`
render() {
		if (this.panelBase == null || this.survey == null || this.creator == null)
			return null;
		if (!this.panelBase.isVisible) return null;
		var title = this.renderTitle();
		var description = this.renderDescription();
		var errors = (
				<SurveyElementErrors
						element={this.panelBase}
						cssClasses={this.panelBase.cssClasses}
						creator={this.creator}
				/>
		);
		var style = {
			paddingLeft: this.panel.innerPaddingLeft,
			display: !this.panel.isCollapsed ? "block" : "none"
		};
		var content = null;

		if (!this.panel.isCollapsed
			||this.hasBeenOpen
		) {
			this.hasBeenOpen=true;
			var rows = this.renderRows();
			content = this.renderContent(style, rows);
		}
		var rootStyle = {};
		if (this.panel.renderWidth) rootStyle["width"] = this.panel.renderWidth;
		var bottom = this.renderBottom();
		return (
				<div ref="root" className={this.css.panel.container} style={rootStyle}>
					{title}
					{description}
					{errors}
					{content}
					{bottom}
				</div>
		);
	}
`

can be a fast way to avoid re render panel once rendered.

**Comment by andrewtelnov** [comment] 2019-07-20 14:19
@marc0n3 Do you guys run any tests? Will it give the peformance improvement?
As I understand the only regression we will have when a collpased panel was opened and then many changes were made in the content. We have te worse situation before, since we do it for a panel that was always collapsed.
If you see that there is a performance improvement, I mean you did some tests and have numbers, I will add this code without any doubts. It seems logical to me. However, sometimes numbers and tests tell opposite to your thoughts.

Thank you,
Andrew

**Comment by marc0n3** [comment] 2019-07-22 07:16
Hi @andrewtelnov,
unfortunately I cannot extract any test from my project right now...

I'm opening a panel that contains several sub panels with lot of questions.
I'm tracing the rendering time of the sub panels when the main panel opens.

FIRST RENDER:
panelpannello10: 171.64501953125ms
panelpannello11: 166.468994140625ms
panelpannello12: 163.330810546875ms
panelpannello26: 158.7529296875ms
panelpannello8: 141.746826171875ms
panelpannello2: 154.0419921875ms
panelpannello3: 139.607177734375ms

CLOSE----

RE-OPEN:
panelpannello10: 188.64208984375ms
panelpannello11: 182.31787109375ms
panelpannello12: 178.0908203125ms
panelpannello26: 173.083984375ms
panelpannello8: 153.325927734375ms
panelpannello2: 169.885986328125ms
panelpannello3: 149.796875ms

same timing again.
This on desktop.
On mobile the situation is far worse with a total time of 1.2sec to render the panel that contains the list of subpanel shown in my timelist.

Of couse this is a critical case, and we've already managed by extending your code.
I was just posting this in case someone else is having the same borderline situation.
The best solution IMHO is to make the user choose panel behavior, if fees the DOM or cache the opened panels, but we don't have time to propose a solution right now.

Many thanks
Marco

**Comment by andrewtelnov** [comment] 2019-07-22 14:24
@marc0n3 Ok, it should work faster with the new minor version.

Thank you,
Andrew

**Closed** 2019-08-01 17:43 UTC
Labels: fixed, perfomance issue
