### ISSUE TITLE
knockout, jquery, angular: Ranking questions doesnt update ordering when choices are in the format {text:"xx", value:"xx"} 

### ISSUE THREAD

**Issue by Mahesh4Providence** [surveyjs/survey-library#2812] opened 2021-04-21 09:30 UTC
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
When user re-orders the ranking choices, the numbering doesnt get updated as per ranking order.

### What is the expected behavior?
When user re-orders the ranking choices, the numbering should get updated as per ranking order.

### How would you reproduce the current behavior (if this is a bug)?
Use this as a test example json provided below.
![Output](https://user-images.githubusercontent.com/67925868/115532696-aa9a0b80-a2b3-11eb-9a93-a4a3b4973f0c.png)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: use the SurveyEditor demo and paste the below json

Test code

```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "ranking",
     "name": "smartphone-features",
     "title": "Please rank the following smartphone features in order of importance:",
     "isRequired": true,
     "choices": [
      {
       "value": "121",
       "text": "Battery life"
      },
      {
       "value": "122",
       "text": "Screen size"
      },
      {
       "value": "124",
       "text": "Storage space"
      },
      {
       "value": "125",
       "text": "Camera quality"
      },
      {
       "value": "126",
       "text": "Durability"
      },
      {
       "value": "127",
       "text": "Processor power"
      },
      {
       "value": "128",
       "text": "Price"
      }
     ]
    }
   ]
  }
 ]
}

```

### Specify your

* browser: Chrome
* browser version: v81.0.4xx
* surveyjs platform (angular or react or jquery or knockout or vue): JQuery
* surveyjs version: 1.8.44 (earlier versions also have this problem)

**Comment by dmitrykurmanov** [comment] 2021-04-21 12:04
Hello, @Mahesh4Providence it is a known bug with the knockout, jquery, and angular versions of survey-library. We are using Sortablejs under the hood for drag and drop and have some conflicts with knockout (jquery and angular are knockout-based versions).

Thanks for the reporting. We will investigate the problem.

**Comment by Mahesh4Providence** [comment] 2021-04-21 12:21
> Hello, @Mahesh4Providence it is a known bug with the knockout, jquery, and angular versions of survey-library. We are using Sortablejs under the hood for drag and drop and have some conflicts with knockout (jquery and angular are knockout-based versions).
> 
> Thanks for the reporting. We will investigate the problem.

Thanks @dmitrykurmanov for the inputs.
Is there any workaround that I can do in the meantime?

**Comment by dmitrykurmanov** [comment] 2021-04-21 12:53
sample for reproduce: https://plnkr.co/edit/zOqJI6pyGzW36z5H

@Mahesh4Providence I will investigate the problem ASAP and try to provide the workaround or the fix.

_ps I am going to try that [knockout-sortable binding](https://github.com/SortableJS/knockout-sortablejs) and I believe that it will fix the issue._

**Comment by dmitrykurmanov** [comment] 2021-04-25 15:30
@Mahesh4Providence I beleave that the problem was fixed via the https://github.com/surveyjs/survey-library/commit/c44851838cbb86dc3c5272b1f2bc653a848cf200. Fix'll be available in the next minor release.

**Closed** 2021-04-28 07:44 UTC
Labels: bug, fixed
