### ISSUE TITLE
hideRequiredErrors not working as expected

### ISSUE THREAD

**Issue by edoorn** [surveyjs/survey-library#2679] opened 2021-02-25 20:54 UTC
### Reporting a bug
hideRequiredErrors property does not work as expected.

### What is the current behavior?
In my survey model, I set `survey.hideRequiredErrors = true;`, but error messages still appear on the page. The values in the `AnswerRequiredError` class look like this:

`{text: "My custom error message text", errorOwner: QuestionDropdownModel, visible: false, locTextValue: LocalizableString}`

Notice that `visible: false` is correctly set in the error class, but the error message is still visible on the web page. I am using the default "checkErrorsMode", which is "onNextPage".

### What is the expected behavior?
By setting `survey.hideRequiredErrors = true;`, I expect that the error messages will not appear on the page. Validation events should still fire.

**Comment by andrewtelnov** [comment] 2021-02-26 06:57
@edoorn We will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment] 2021-02-26 11:22
@edoorn I have fixed by the commit above. The fix will be available in [v1.8.33](https://surveyjs.io/WhatsNew#v1.8.33).

Thank you,
Andrew

**Closed** 2021-03-03 19:59 UTC
Labels: bug, fixed

**Comment by a-d-c** [comment] 2021-03-16 14:32
Hi there,

After this fix was added to v1.8.33 I noticed the following. Upon navigating between pages of the survey we are persisting survey data to our server and it is possible that the server will return an error (note that we explicitly are doing this as part of the save process and not as a "server side validation" because the cause of the error could be a relationship between various answers across pages and other server side context.

At any rate, in the error handler of the save I have the following:

targetQuestion.addError(new Survey.SurveyError(error.error.userErrorMessage));

Prior to v 1.8.33 I would immediately see the error appear on the page. After this change I have to force the error to appear by adding:

targetQuestion.hasVisibleErrors = true;

My question is - does this seem like an acceptable/safe workaround? 

Thanks!

**Comment by andrewtelnov** [comment] 2021-03-16 16:11
@a-d-c Why don't you use [survey.onValidateQuestion](https://surveyjs.io/Documentation/Library?id=surveymodel#onValidateQuestion) and [survey.onServerValidateQuestions](https://surveyjs.io/Documentation/Library?id=surveymodel#onServerValidateQuestions) errors?
It is a standard approach. Here is [the example](https://surveyjs.io/Examples/Library?id=validators-server). You can try to save the data `onServerValidateQuestions`  event.

Thank you,
Andrew
